name: Deploy to AWS Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: cd api && npm run install-all

      - name: Zip get-itinerary code
        run: zip -r get-itinerary.zip ./api/get-itinerary

      - name: Wait for Lambda to be ready (enhanced check)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
        run: |
          echo "Waiting for Lambda to be ready..."
          for i in {1..20}; do
            CONFIG=$(aws lambda get-function-configuration \
              --function-name get-itinerary \
              --region "$AWS_REGION")
            STATUS=$(echo "$CONFIG" | jq -r '.LastUpdateStatus')
            LAST_MODIFIED=$(echo "$CONFIG" | jq -r '.LastModified')
            LAST_MODIFIED_UNIX=$(date -d "$LAST_MODIFIED" +%s)
            NOW_UNIX=$(date +%s)
            AGE=$((NOW_UNIX - LAST_MODIFIED_UNIX))

            echo "Status: $STATUS, Age: ${AGE}s"

            if [ "$STATUS" = "Successful" ] && [ "$AGE" -gt 60 ]; then
              echo "Lambda is ready for update"
              break
            elif [ "$i" -eq 20 ]; then
              echo "Timeout waiting for Lambda readiness"
              exit 1
            else
              echo "Still updating or too recent. Retrying in 10s..."
              sleep 10
            fi
          done

      - name: Upload get-itinerary to AWS Lambda
        uses: appleboy/lambda-action@v0.1.7
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: get-itinerary
          zip_file: get-itinerary.zip
