name: Deploy to AWS Lambda

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install get itinerary dependencies
        working-directory: api/get-itinerary
        run: npm install

      - name: Install get existing tour dependencies
        working-directory: api/get-existing-tour
        run: npm install
      

      - name: Zip get-itinerary code
        run: cd api/get-itinerary && zip -r index.zip .

      - name: Zip get-place-photo code
        run: cd api/get-place-photo && zip -r index.zip .
      
      - name: Zip ask-question code
        run: cd api/ask-question && zip -r index.zip .

      - name: Zip get-existing-tour code
        run: cd api/get-existing-tour && zip -r index.zip .

      - name: Zip share-feedback-tour code
        run: cd api/share-feedback && zip -r index.zip .

      - name: Upload get-itinerary to AWS Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: get-itinerary
          zip_file: api/get-itinerary/index.zip

      - name: Upload get-place-photo to AWS Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: get-place-photo
          zip_file: api/get-place-photo/index.zip
      
      - name: Upload ask-question to AWS Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: ask-question 
          zip_file: api/ask-question/index.zip

      - name: Upload get-existing-tour to AWS Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: get-existing-tour 
          zip_file: api/get-existing-tour/index.zip
      
      - name: Upload share-feedback to AWS Lambda
        uses: appleboy/lambda-action@v0.2.0
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: share-feedback 
          zip_file: api/share-feedback/index.zip
